version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
      - POSTGRES_DB=budgets
    volumes:
    - db_data:/var/lib/postgresql/data

  web:
    container_name: web
    build: backend
    command: gunicorn budgets.wsgi:application --bind 0.0.0.0:80
    volumes:
      - ./backend:/app
    ports:
     - "80:80"
    env_file:
      - backend/.env
    environment:
      - DEBUG=0
    depends_on:
     - db

  ng:
    container_name: ng
    build: frontend
    ports:
      - "8000:80"

volumes:
  db_data: