version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_pass
      - POSTGRES_USER=postgres_user
  web:
    container_name: web
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
     - "8000:8000"
    depends_on:
     - db
