# Generated by Django 3.2.9 on 2021-12-07 06:48

from django.apps.registry import Apps
from django.contrib.auth.hashers import make_password
from django.db import migrations


def add_default_user(apps: Apps, schema_editor):
    User = apps.get_model("main", "User")

    User.objects.get_or_create(
        username="admin",
        defaults={
            "email": "admin@example.com",
            "is_staff": True,
            "is_superuser": True,
            "password": make_password("admin"),
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_budget_budgetitem_budgetitemcategory'),
    ]

    operations = [
        migrations.RunPython(
            add_default_user,
            reverse_code=migrations.RunPython.noop,
            elidable=False,
        )
    ]
